#!/bin/sh

export PATH="/usr/local/bin:$PATH"

# Prevent committing to main branch
CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
if [ "$CURRENT_BRANCH" == "main"  ] || [ "$CURRENT_BRANCH" == "master"  ]; then
  echo "You are not allowed to commit directly to the main/master branch. Please create a feature branch and make a pull request."
  exit 1
fi 

# Run checks
npx lint-staged
npx tsc --noEmit --noUnusedLocals  

RETURN=$?

if [ $RETURN -ne 0 ];
then
  echo "@@@@@@ Pre-commit checks failed! Please fix your code before committing! @@@@@@"
  exit $RETURN
fi
