name: Build and Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{vars.SERVER_IP}} >> ~/.ssh/known_hosts

      - name: Build and Deploy Web
        working-directory: web
        env:
          REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
        run: |
          npm install
          npm run build
          scp -r ./build/* root@116.203.211.123://root/projects/portfolio/web_build

      - name: Build and deploy API
        working-directory: api
        run: |
          rsync -av --exclude=node_modules --exclude=dist ./ root@116.203.211.123:/root/projects/portfolio/api

      - name: Run Commands on Remote Server
        run: |
          ssh root@116.203.211.123 << EOF
            cd projects/nestjs-github-activity
            npm link
            cd ../portfolio/api
            pkill -f node
            npm install
            npm link nestjs-github-activity
            npm run build
            npm run start:prod
          EOF
